#!/bin/bash

COMMIT=$(git rev-parse --short HEAD)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Executing hook ($COMMIT, $BUILD_DATE) ..."

docker build \
  --build-arg COMMIT=$COMMIT \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .
